# backend/dockerfile
FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# Agrega dependencias de desarrollo para migraciones
RUN npm install ts-node tsconfig-paths -D

# Arranca usando un script personalizado
CMD ["sh", "./entrypoint.sh"]
